language: cpp
matrix:
    include:
    - os: linux
      dist: xenial
      sudo: required
      addons:
          apt:
              sources:
                  - https://packages.lunarg.com/vulkan/1.2.141
              packages:
                  - vulkan-sdk
                  - build-essential
                  - cmake
                  - zlib1g-dev
                  - libboost-filesystem-dev
                  - libboost-system-dev
                  - libboost-regex-dev
    - os: osx
script:
    - cmake -DNOGUI=YES . && cmake --build .
    - bin/testproject
