language: cpp
git:
  depth: 1
matrix:
    include:
    - os: linux
      dist: xenial
      sudo: required
      addons:
          apt:
              sources:
                  - sourceline: deb https://packages.lunarg.com/vulkan/1.2.141 xenial main
                    key_url: https://packages.lunarg.com/lunarg-signing-key-pub.asc
              packages:
                  - vulkan-sdk
                  - build-essential
                  - cmake
                  - zlib1g-dev
                  - libboost-filesystem-dev
                  - libboost-system-dev
                  - libboost-regex-dev
    - os: osx
      osx_image: xcode12.4
      addons:
        homebrew:
          update: true
          taps: apenngrace/vulkan
          casks: vulkan-sdk
          packages:
            - boost
            - cmake
            - zlib
script:
    - cmake -DNOGUI=YES . && cmake --build .
    - bin/testproject
