version: 1.0.0.{build}
image: Visual Studio 2019
pull_requests:
  do_not_increment_build_number: true
clone_depth: 1
environment:
  VCPKG_DIR: C:\Tools\vcpkg
  MY_BOOST_ROOT: C:\projects\boost
  MY_BOOST_INCLUDEDIR: C:\projects\boost
  MY_BOOST_LIBRARYDIR: C:\projects\boost\stage\lib
  MY_Qt6Widgets_DIR: C:\Qt\6.0.1\msvc2019_64\lib\cmake\Qt5Widgets
  QT_PATH: C:\Qt\6.0.1\msvc2019_64

init:
- ps: Set-WinSystemLocale ru-RU
- ps: Start-Sleep -s 5
- ps: Restart-Computer
install:
- call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
- cd %VCPKG_DIR%
- git pull
- call .\bootstrap-vcpkg.bat
- .\vcpkg --triplet x64-windows install boost-filesystem
- .\vcpkg --triplet x64-windows install boost-system
- .\vcpkg --triplet x64-windows install boost-regex
- .\vcpkg --triplet x64-windows install boost-random
- .\vcpkg --triplet x64-windows install boost-uuid
- .\vcpkg --triplet x64-windows install boost-crc
- .\vcpkg --triplet x64-windows install zlib
- cd %APPVEYOR_BUILD_FOLDER%
build_script:
- cmd: >-
    mkdir tool1cd

    cd tool1cd

    cmake -DCMAKE_BUILD_TYPE=Release
    -DVCPKG_TARGET_ARCHITECTURE=x64
    -DCMAKE_PREFIX_PATH=%QT_PATH%
    -DCMAKE_TOOLCHAIN_FILE=%VCPKG_DIR%/scripts/buildsystems/vcpkg.cmake
    -DQt6Widgets_DIR="%MY_Qt6Widgets_DIR%"
    ..

    cmake --build . --target gtool1cd

    cmake --build . --target ctool1cd

    cmake --build . --target testproject

    cd ..

test_script:
- tool1cd\bin\testproject.exe --reporter junit --out junit.xml

on_finish:
- ps: >-
    $wc = New-Object 'System.Net.WebClient'

    $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\junit.xml))

after_build:
- cmd: >-
    SET PATH=%PATH%;"%WIX%/bin";"%QT_PATH%/bin"

    windeployqt.exe --release --no-compiler-runtime --no-translations
    --no-system-d3d-compiler --no-opengl-sw --no-angle --no-patchqt
    tool1cd\bin\gtool1cd.exe

    call .\windeploycrt.cmd %QT_PATH%\bin tool1cd\bin

    xcopy COPYING tool1cd\bin

    7z a -r tool1cd-%APPVEYOR_BUILD_VERSION%.zip tool1cd\bin

    candle tool1cd.wxs

    light -out tool1cd-%APPVEYOR_BUILD_VERSION%.msi tool1cd.wixobj

artifacts:
- path: tool1cd\bin\ctool1cd.exe
  name: ctool1cd.exe
- path: tool1cd-*.zip
  name: tool1cd.zip
- path: tool1cd-*.msi
  name: installer
deploy: false
